# Config file for the plugin SulfurFun

# Set permissions for commands. Format: command: permission
# You can use op (-> for operators only), true (-> for everyone), false (-> for no one)
permissions_for_commands:
    football: true
    newarena: op

### WARNING: DANGEROUS SETTINGS BELOW! DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING! ###

ConfigVersion: 1.0