name: SulfurFun
description: $description
version: '${version}'

main: de.jgaertig.sulfurFun.SulfurFun
api-version: '26.1.2'

authors: [ j-gaertig ]
website: https://github.com/j-gaertig/SulfurFun

commands:
  football:
    usage: /football
  newarena:
    usage: /newarena <gamemode> <arena_id>
    permission: operator