name: SulfurFun
description: $description
version: '${version}'

main: de.jgaertig.sulfurFun.SulfurFun
api-version: '26.1.2'

authors: [ j-gaertig ]
website: https://github.com/j-gaertig/SulfurFun

commands:
  football:
    usage: /football
    aliases: [soccer]
  newarena:
    usage: /newarena <gamemode> <arena_id>
  deletearena:
    usage: /deletearena <arena_id>
  listarenas:
    usage: /listarenas [arena_id]