name: "🐛 Bug Report"
description: "Report a bug!"
labels: ["bug"]
body:

  - type: input
    id: servertype
    attributes:
      label: "On which server type did this occur? Paper, Spigot, ..."
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe your bug!"
    validations:
      required: true
