name: SulfurFun
description: $description
version: '0.0.3-Experimental'

main: de.jgaertig.sulfurFun.SulfurFun
api-version: '26.1.2'

authors: [ j-gaertig ]
website: https://github.com/j-gaertig/SulfurFun

commands:
  football:
    usage: /football
  newarena:
    usage: /newgame <gamemode>
    permission: operator